server {
    listen 8080;

    location /api/users/ {
        proxy_pass http://users:5001/;
    }

    location /api/products/ {
        proxy_pass http://products:5002/;
    }

    location /api/orders/ {
        proxy_pass http://orders:5003/;
    }
}
